config/routes.rb
MTSDip::Application.routes.draw do

  get "test/index"

  resources :user_statuses

  match 'users/login' => 'users#login'
  resources :users
  
  resources :tickets

  resources :specializations

  get "main/home"

  match "home/:arg" => "main#home"
  match "test" => "test#index", :via => "get"   

  root :to => 'main#home'

  resources :doctors
  
  get 'weekly_schedules/get-schedule' => 'weekly_schedules#getschedule'

  get 'weekly_schedules' => 'weekly_schedules#index'

  get 'weekly_schedules/:id' => 'weekly_schedules#show'

  delete 'weekly_schedules/:id' => 'weekly_schedules#destroy'

  post 'weekly_schedules' => 'weekly_schedules#create'

  put 'weekly_schedules/:id'  => 'weekly_schedules#update'

  match 'weekly_schedules/getbydoc/:doctor_id' => 'weekly_schedules#getbydoc'
  
  match 'weekly_schedules/:id/getduration' => 'weekly_schedules#getduration'

  match 'tickets/:user_id/doctor_name' => 'tickets#doctor_name'

  match 'user_statuses/:id/addmiss' => 'user_statuses#addmiss'

  match 'user_statuses/:id/removemiss' => 'user_statuses#removemiss'

  match '/:route' => 'main#home'  

  

end

app/controllers/user_statuses_controller.rb
class UserStatusesController < ApplicationController
  # GET /user_statuses
  # GET /user_statuses.json
  def index
    @user_statuses = UserStatus.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @user_statuses }
    end
  end

  # GET /user_statuses/1
  # GET /user_statuses/1.json
  def show
    @user_status = UserStatus.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user_status }
    end
  end

  # GET /user_statuses/new
  # GET /user_statuses/new.json
  def new
    @user_status = UserStatus.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user_status }
    end
  end

  # GET /user_statuses/1/edit
  def edit
    @user_status = UserStatus.find(params[:id])
  end

  # POST /user_statuses
  # POST /user_statuses.json
  def create
    @user_status = UserStatus.new(params[:user_status])

    respond_to do |format|
      if @user_status.save
        format.html { redirect_to @user_status, notice: 'User status was successfully created.' }
        format.json { render json: @user_status, status: :created, location: @user_status }
      else
        format.html { render action: "new" }
        format.json { render json: @user_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /user_statuses/1
  # PUT /user_statuses/1.json
  def update
    @user_status = UserStatus.find(params[:id])

    respond_to do |format|
      if @user_status.update_attributes(params[:user_status])
        format.html { redirect_to @user_status, notice: 'User status was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_statuses/1
  # DELETE /user_statuses/1.json
  def destroy
    @user_status = UserStatus.find(params[:id])
    @user_status.destroy

    respond_to do |format|
      format.html { redirect_to user_statuses_url }
      format.json { head :no_content }
    end
  end
# AddMiss /user_statuses/1/addmiss
  def addmiss
    @user_status = UserStatus.find(params[:id])
    @user_status.missing_count += 1
    

    if @user_status.missing_count <= 3
      @user_status.status = "active"
    else
      @user_status.status = "blocked"
    end
    @user_status.save
    respond_to do |format|
      format.json { render json: @user_status}
    end
  end
# RemoveMiss /user_statuses/1/removemiss
def removemiss
    @user_status = UserStatus.find(params[:id])
    @user_status.missing_count -= 1

    if @user_status.missing_count <= 3
      @user_status.status = "active"
    else
      @user_status.status = "blocked"
    end
    @user_status.save
    respond_to do |format|
      format.json { render json: @user_status}
    end
  end
end

app/helpers/user_statuses_helper.rb
module UserStatusesHelper
end

app/views/user_statuses/_form.html.erb
<%= form_for(@user_status) do |f| %>
  <% if @user_status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_status.errors.count, "error") %> prohibited this user_status from being saved:</h2>

      <ul>
      <% @user_status.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :missing_count %><br />
    <%= f.number_field :missing_count %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_statuses/edit.html.erb
<h1>Editing user_status</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_status %> |
<%= link_to 'Back', user_statuses_path %>

app/views/user_statuses/index.html.erb
<h1>Listing user_statuses</h1>

<table>
  <tr>
    <th>Missing count</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @user_statuses.each do |user_status| %>
  <tr>
    <td><%= user_status.missing_count %></td>
    <td><%= link_to 'Show', user_status %></td>
    <td><%= link_to 'Edit', edit_user_status_path(user_status) %></td>
    <td><%= link_to 'Destroy', user_status, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User status', new_user_status_path %>

app/views/user_statuses/new.html.erb
<h1>New user_status</h1>

<%= render 'form' %>

<%= link_to 'Back', user_statuses_path %>

app/views/user_statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Missing count:</b>
  <%= @user_status.missing_count %>
</p>


<%= link_to 'Edit', edit_user_status_path(@user_status) %> |
<%= link_to 'Back', user_statuses_path %>