config/routes.rb
MTSDip::Application.routes.draw do

  get "test/index"

  resources :user_statuses

  match 'users/login' => 'users#login'
  resources :users
  
  resources :tickets

  resources :specializations

  get "main/home"

  match "home/:arg" => "main#home"
  match "test" => "test#index", :via => "get"   

  root :to => 'main#home'

  resources :doctors
  
  get 'weekly_schedules/get-schedule' => 'weekly_schedules#getschedule'

  get 'weekly_schedules' => 'weekly_schedules#index'

  get 'weekly_schedules/:id' => 'weekly_schedules#show'

  delete 'weekly_schedules/:id' => 'weekly_schedules#destroy'

  post 'weekly_schedules' => 'weekly_schedules#create'

  put 'weekly_schedules/:id'  => 'weekly_schedules#update'

  match 'weekly_schedules/getbydoc/:doctor_id' => 'weekly_schedules#getbydoc'
  
  match 'weekly_schedules/:id/getduration' => 'weekly_schedules#getduration'

  match 'tickets/:user_id/doctor_name' => 'tickets#doctor_name'

  match 'user_statuses/:id/addmiss' => 'user_statuses#addmiss'

  match 'user_statuses/:id/removemiss' => 'user_statuses#removemiss'

  match '/:route' => 'main#home'  

  

end

app/models/specialization.rb
class Specialization < ActiveRecord::Base
  attr_accessible :name
  has_many :doctors
end

app/controllers/specializations_controller.rb
class SpecializationsController < ApplicationController
  # GET /specializations
  # GET /specializations.json
  def index
    @specializations = Specialization.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @specializations }
    end
  end

  # GET /specializations/1
  # GET /specializations/1.json
  def show
    @specialization = Specialization.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @specialization }
    end
  end

  # GET /specializations/new
  # GET /specializations/new.json
  def new
    @specialization = Specialization.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @specialization }
    end
  end

  # GET /specializations/1/edit
  def edit
    @specialization = Specialization.find(params[:id])
  end

  # POST /specializations
  # POST /specializations.json
  def create
    @specialization = Specialization.new(params[:specialization])

    respond_to do |format|
      if @specialization.save
        format.html { redirect_to @specialization, notice: 'Specialization was successfully created.' }
        format.json { render json: @specialization, status: :created, location: @specialization }
      else
        format.html { render action: "new" }
        format.json { render json: @specialization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /specializations/1
  # PUT /specializations/1.json
  def update
    @specialization = Specialization.find(params[:id])

    respond_to do |format|
      if @specialization.update_attributes(params[:specialization])
        format.html { redirect_to @specialization, notice: 'Specialization was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @specialization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /specializations/1
  # DELETE /specializations/1.json
  def destroy
    @specialization = Specialization.find(params[:id])
    @specialization.destroy

    respond_to do |format|
      format.html { redirect_to specializations_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/specializations_helper.rb
module SpecializationsHelper
end

app/views/specializations/_form.html.erb
<%= form_for(@specialization) do |f| %>
  <% if @specialization.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@specialization.errors.count, "error") %> prohibited this specialization from being saved:</h2>

      <ul>
      <% @specialization.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/specializations/edit.html.erb
<h1>Editing specialization</h1>

<%= render 'form' %>

<%= link_to 'Show', @specialization %> |
<%= link_to 'Back', specializations_path %>

app/views/specializations/index.html.erb
<h1>Listing specializations</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @specializations.each do |specialization| %>
  <tr>
    <td><%= specialization.name %></td>
    <td><%= link_to 'Show', specialization %></td>
    <td><%= link_to 'Edit', edit_specialization_path(specialization) %></td>
    <td><%= link_to 'Destroy', specialization, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Specialization', new_specialization_path %>

app/views/specializations/new.html.erb
<h1>New specialization</h1>

<%= render 'form' %>

<%= link_to 'Back', specializations_path %>

app/views/specializations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @specialization.name %>
</p>


<%= link_to 'Edit', edit_specialization_path(@specialization) %> |
<%= link_to 'Back', specializations_path %>