config/routes.rb
MTSDip::Application.routes.draw do

  get "test/index"

  resources :user_statuses

  match 'users/login' => 'users#login'
  resources :users
  
  resources :tickets

  resources :specializations

  get "main/home"

  match "home/:arg" => "main#home"
  match "test" => "test#index", :via => "get"   

  root :to => 'main#home'

  resources :doctors
  
  get 'weekly_schedules/get-schedule' => 'weekly_schedules#getschedule'

  get 'weekly_schedules' => 'weekly_schedules#index'

  get 'weekly_schedules/:id' => 'weekly_schedules#show'

  delete 'weekly_schedules/:id' => 'weekly_schedules#destroy'

  post 'weekly_schedules' => 'weekly_schedules#create'

  put 'weekly_schedules/:id'  => 'weekly_schedules#update'

  match 'weekly_schedules/getbydoc/:doctor_id' => 'weekly_schedules#getbydoc'
  
  match 'weekly_schedules/:id/getduration' => 'weekly_schedules#getduration'

  match 'tickets/:user_id/doctor_name' => 'tickets#doctor_name'

  match 'user_statuses/:id/addmiss' => 'user_statuses#addmiss'

  match 'user_statuses/:id/removemiss' => 'user_statuses#removemiss'

  match '/:route' => 'main#home'  

  

end

app/models/ticket.rb
class Ticket < ActiveRecord::Base

   attr_accessible :data, :time, :doctor_id, :user_id, :status 
     
   belongs_to :user
   belongs_to :doctor
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  # GET /tickets
  # GET /tickets.json
  def index
    
    if params["doctor_id"] != nil
      @tickets = Ticket.where(:doctor_id => params["doctor_id"], :data => params["data"]);

    elsif params["data"] != nil and  params["user_id"] != nil      
      @tickets = Ticket.where(user_id:params["user_id"], data:params["data"]);
    else
      @tickets = Ticket.all
        
    end  

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tickets }
    end
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
    @ticket = Ticket.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ticket }
    end
  end

  # GET /tickets/new
  # GET /tickets/new.json
  def new
    @ticket = Ticket.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ticket }
    end
  end

  # GET /tickets/1/edit
  def edit
    @ticket = Ticket.find(params[:id])
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = Ticket.new(params[:ticket])

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
        format.json { render json: @ticket, status: :created, location: @ticket }
      else
        format.html { render action: "new" }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tickets/1
  # PUT /tickets/1.json
  def update
    @ticket = Ticket.find(params[:id])

    respond_to do |format|
      if @ticket.update_attributes(params[:ticket])
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket = Ticket.find(params[:id])
    @ticket.destroy

    respond_to do |format|
      format.html { redirect_to tickets_url }
      format.json { head :no_content }
    end
  end

  #GET /tickets/1/doctor_name
  #GET /tickets/1/doctor_name.json
  def doctor_name
    @tickets = Ticket.where(:user_id => params[:user_id])

    out = []
    @tickets.each do |t|
      info = {:user_id => t.user_id, :doctor_id => t.doctor_id, :doctor_name => t.doctor.name, :data => t.data, :time => t.time}
      out.push info
    end

    respond_to do |format|
      format.json { render json: out}
    end
  end
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/tickets/_form.html.erb
<%= form_for(@ticket) do |f| %>
  <% if @ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
      <% @ticket.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date_time %><br />
    <%= f.text_field :date_time %>
  </div>
  <div class="field">
    <%= f.label :doctor_id %><br />
    <%= f.number_field :doctor_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tickets/edit.html.erb
<h1>Editing ticket</h1>

<%= render 'form' %>

<%= link_to 'Show', @ticket %> |
<%= link_to 'Back', tickets_path %>

app/views/tickets/index.html.erb
<h1>Listing tickets</h1>

<table>
  <tr>
    <th>Date time</th>
    <th>Doctor</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tickets.each do |ticket| %>
  <tr>
    <td><%= ticket.date_time %></td>
    <td><%= ticket.doctor_id %></td>
    <td><%= link_to 'Show', ticket %></td>
    <td><%= link_to 'Edit', edit_ticket_path(ticket) %></td>
    <td><%= link_to 'Destroy', ticket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Ticket', new_ticket_path %>

app/views/tickets/new.html.erb
<h1>New ticket</h1>

<%= render 'form' %>

<%= link_to 'Back', tickets_path %>

app/views/tickets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Date time:</b>
  <%= @ticket.date_time %>
</p>

<p>
  <b>Doctor:</b>
  <%= @ticket.doctor_id %>
</p>


<%= link_to 'Edit', edit_ticket_path(@ticket) %> |
<%= link_to 'Back', tickets_path %>